version: '3'

services:
  frontend:
    image: snibox/nginx-puma:1.15.9
    volumes:
      - static-files:/var/www/html
    depends_on:
      - backend
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.permanent=true"
      - "traefik.http.routers.snibox.rule=Host(`${SNIBOX_DOMAIN}`)"
      - "traefik.http.routers.snibox.entryPoints=web"
      - "traefik.http.routers.snibox.middlewares=redirect-to-https"
      - "traefik.http.routers.snibox-https.rule=Host(`${SNIBOX_DOMAIN}`)"
      - "traefik.http.routers.snibox-https.entryPoints=websecure"
      - "traefik.http.routers.snibox-https.tls=true"
      - "traefik.http.routers.snibox-https.tls.certresolver=letsencrypt"

  backend:
    image: snibox/snibox:latest
    command: sh -c "rm -rf tmp/pids && ./bin/rails s -p 3000 -b '0.0.0.0'"
    networks:
      - traefik
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      FORCE_SSL: "false"
      MAILGUN_SMTP_PORT: "${MAILGUN_SMTP_PORT}"
      MAILGUN_SMTP_SERVER: "${MAILGUN_SMTP_SERVER}"
      MAILGUN_SMTP_LOGIN: "${MAILGUN_SMTP_LOGIN}"
      MAILGUN_SMTP_PASSWORD: "${MAILGUN_SMTP_PASSWORD}"
      MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"
      MAILGUN_PUBLIC_KEY: "${MAILGUN_PUBLIC_KEY}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    volumes:
      - static-files:/app/public
    labels:
      - "traefik.enable=true"

volumes:
  static-files:

networks:
  traefik:
    external:
      name: traefik